name = "my-test"
account_id = "c1225def766dac25afe2b8859f7a4623"
compatibility_flags = []
workers_dev = true
compatibility_date = "2023-01-28"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "my-app-todo"
database_id = "47aa688a-80e7-40ba-a5de-618173b42256"
migrations_dir = "db/migrations"

[[d1_databases]]
binding = "DB_preview" # i.e. available in your Worker on env.DB
database_name = "my-app-todo_preview"
database_id = "5e6a6503-bdf0-45ff-9cae-11d6328eb393"
migrations_dir = "db/migrations"
